name: Labeler Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
